name = "7th-heaven"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

# KV binding for storing purge history logs
[[kv_namespaces]]
binding = "PURGE_HISTORY"
id = "d636725384ff42d3915e22ac382c9bad"
preview_id = "f75b59eb33d1489d8afeed4564b19539"

# Vars
# Found at => .dev.vars 