# .github/workflows/auto-append-deploy-tags.yml
name: Auto Append Deploy Tags

on:
  push:
    branches:
      - staging
      - '!auto/**'
  schedule:
    - cron: '0 9 * * 1'

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: deploy-changelog-${{ github.ref_name }}
  cancel-in-progress: false

env:
  TAG_REGEX: '(#add-post:|#delete-post:|#update-section:)[^[:space:]]+'

jobs:
  append-deploy-tags:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: staging

      - name: 🔍 Collect deploy tags
        id: extract
        shell: bash
        run: |
          set -euo pipefail

          # Pull unique deploy‐tags from the last 20 commit messages.
          # '|| true' keeps the step green when no matches are found.
          tags=$(git log -n 20 --pretty=format:%s \
                 | grep -Eo "$TAG_REGEX" | sort -u || true)

          if [[ -z "$tags" ]]; then
            echo "No deploy tags found in the last 20 commits."
          fi

          {
            echo 'tags<<EOF'
            printf '%s\n' "$tags"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: 📄 Append to deploy-changelog.md
        if: steps.extract.outputs.tags != ''
        shell: bash
        run: |
          {
            printf '\n# Auto-appended on %s\n' "$(date +%F)"
            echo 'Deploy tags:'
            printf '%s\n' "${{ steps.extract.outputs.tags }}" | sed 's/^/* /'
          } >> deploy-changelog.md

      - name: 🤖 Create pull request
        if: steps.extract.outputs.tags != ''
        uses: peter-evans/create-pull-request@v5
        with:
          branch: auto/deploy-changelog
          base: staging
          commit-message: "chore(deploy): auto-update deploy changelog"
          title:  "chore(deploy): auto-update deploy changelog"
          body: |
            This PR appends the latest deploy tags to **deploy-changelog.md**.
            (_Auto-generated by **Auto Append Deploy Tags** workflow._)
          labels: |
            type:chore
            target:staging
          delete-branch: true
