name: Weekly Release
on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: Set up Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge staging into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/staging --no-edit
          git push origin main