#!/bin/sh

echo "✉️  Husky commit-msg hook triggered"

# Optional: log timestamp to .husky/log.txt
echo "[COMMIT-MSG] $(date) by $(whoami)" >> .husky/log.txt

npx commitlint --edit "$1"

# if using selectve-deploy
# test if deploy-from-changelog configured correctly
# echo "🧪  test:fixtures hook triggered"

# npm run test:fixtures
