name: CI + Semantic Release

on:
  push:
    branches:
      - staging
      - 'release/*'
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      # 1) create 1-hour installation token
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id:      ${{ secrets.HEAVB_SV_ID }}   # numeric App ID
          private-key: ${{ secrets.HEAVB_SV_KEY }}  # full PEM

      # 2) checkout with that token
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      # 3) node setup & install
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      # 4) run semantic-release with the same token
      - name: Run semantic-release
        env:
          GH_TOKEN:     ${{ steps.app-token.outputs.token }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: npx semantic-release
