name: 🛑 Report client-tests failures to Jira

on:
  workflow_run:
    workflows: ["Client Tests"]
    types: [completed]

jobs:
  report:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: ⬇️  Download workflow logs
        id: logs
        run: |
          gh run download ${{ github.event.workflow_run.id }} -n client-tests-logs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📝  Report to Jira (deduped)
        run: |
          cat client-tests-logs/*.txt | \
            node scripts/report-jira.js \
              --source ci-failure \
              --job "${{ github.event.workflow.name }}" \
              --run-url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          JIRA_BASE_URL:  ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
